ASPNetApp/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ASPNetApp.Models
{
    public class LoginViewModel
    {
        [Required]
        [Display(Name = "Логин")]
        public string UserName { get; set; }

        [Required]
        [UIHint("password")]
        [Display(Name = "Пароль")]
        public string Password { get; set; }

        [Required]
        [Display(Name = "Запомнить меня")]
        public bool RememberMe { get; set; }
    }
}

ASPNetApp/Areas/Admin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ASPNetApp.Domain;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;

namespace ASPNetApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HomeController : Controller
    {
        private readonly DataManager DataManager;


        public HomeController(DataManager dataManager)
        {
            DataManager = dataManager;
        }

        public IActionResult Index()
        {
            return View(DataManager.ProjectItems.GetAllProjectItems());
        }
    }
}

ASPNetApp/Areas/Admin/Controllers/ProjectItemsController.cs
using ASPNetApp.Domain;
using ASPNetApp.Domain.Entities;
using ASPNetApp.Service;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ASPNetApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProjectItemsController : Controller
    {
        private readonly DataManager DataManager;
        private readonly IWebHostEnvironment HostingEnvironment;

        public ProjectItemsController(DataManager dataManager, IWebHostEnvironment hostingEnvironment)
        {
            DataManager = dataManager;
            HostingEnvironment = hostingEnvironment;
        }

        public IActionResult Edit(Guid id)
        {
            var entity = id == default ? new ProjectItem() : DataManager.ProjectItems.GetProjectItemById(id);
            return View(entity);
        }

        [HttpPost]
        public IActionResult Edit(ProjectItem projectModel, IFormFile urlToPreview)
        {
            if (ModelState.IsValid)
            {
                if (urlToPreview != null)
                {
                    projectModel.UrlToPreview = urlToPreview.FileName;
                    using (var stream = new FileStream(Path.Combine(HostingEnvironment.WebRootPath, "images/", projectModel.UrlToPreview), FileMode.Create))
                    {
                        urlToPreview.CopyTo(stream);
                    }
                }
                DataManager.ProjectItems.SaveProjectItem(projectModel);
                return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
            }
            return View(projectModel);
        }

        [HttpPost]
        public IActionResult Delete(Guid id)
        {
            DataManager.ProjectItems.DeleteProjectItem(id);
            return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
        }

    }
}

ASPNetApp/Areas/Admin/Controllers/TextFieldsController.cs
using ASPNetApp.Domain;
using ASPNetApp.Domain.Entities;
using ASPNetApp.Service;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web;

namespace ASPNetApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class TextFieldsController : Controller
    {
        public readonly DataManager DataManager;

        public TextFieldsController(DataManager dataManager)
        {
            DataManager = dataManager;
        }

        public IActionResult Edit(string codeWord)
        {
            var entity = DataManager.TextFields.GetTextFieldByCodeWord(codeWord);
            return View(entity);
        }

        [HttpPost]
        public IActionResult Edit(TextField textFieldModel)
        {
            if(ModelState.IsValid)
            {
                //textFieldModel.Text = HttpUtility.HtmlEncode(textFieldModel.Text);
                DataManager.TextFields.SaveTextField(textFieldModel);
                return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
            }
            return View(textFieldModel);
        }
    }
}

ASPNetApp/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ASPNetApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace ASPNetApp.Controllers
{
    [Authorize]
    public class AccountController : Controller
    {
        private readonly UserManager<IdentityUser> userManager;
        private readonly SignInManager<IdentityUser> signInManager;

        public AccountController(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
        }

        [AllowAnonymous]
        public IActionResult Login(string returnUrl)
        {
            ViewBag.returnUrl = returnUrl;
            return View(new LoginViewModel());
        }
        [HttpPost]
        [AllowAnonymous]
        public async Task<ActionResult> Login(LoginViewModel model, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                IdentityUser user = await userManager.FindByNameAsync(model.UserName);
                if(user != null)
                {
                    await signInManager.SignOutAsync();
                    Microsoft.AspNetCore.Identity.SignInResult result = await signInManager.PasswordSignInAsync(user, model.Password, model.RememberMe, false);
                    if(result.Succeeded)
                    {
                        return Redirect(returnUrl ?? "/");
                    }
                }
                ModelState.AddModelError(nameof(LoginViewModel.UserName), "Неверный логин или пароль");
            }
            return View(model);
        }

        [Authorize]
        public async Task<ActionResult> Logout()
        {
            await signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
    }
}

ASPNetApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ASPNetApp.Domain;
using Microsoft.AspNetCore.Mvc;

namespace ASPNetApp.Controllers
{
    public class HomeController : Controller
    {

        private readonly DataManager DataManager;

        public HomeController(DataManager dataManager)
        {
            DataManager = dataManager;
        }

        public IActionResult Index()
        {
            return View(DataManager);
        }

        public IActionResult Contacts()
        {
            return View(DataManager.TextFields.GetTextFieldByCodeWord("PageContacts"));
        }


    }
}

ASPNetApp/Controllers/ProjectController.cs
using ASPNetApp.Domain;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ASPNetApp.Controllers
{
    public class ProjectController: Controller
    {
        private readonly DataManager DataManager;

        public ProjectController(DataManager dataManager)
        {
            DataManager = dataManager;
        }

    }
}

ASPNetApp/Areas/Admin/Views/Home/Index.cshtml
@model IQueryable<ProjectItem>
@{
    ViewData["Title"] = "Панель администратора";
}

<div>
    <h1>@ViewData["Title"]</h1>
    <div class="container">
        <a asp-area="Admin" asp-controller="ProjectItems" asp-action="Edit" asp-route-id="">Добавить услугу</a>
    </div>
    @if (Model.Any())
    {
        <div class="container">
            @foreach (var entity in Model)
            {
                <a asp-area="Admin" asp-controller="ProjectItems" asp-action="Edit" asp-route-id="@entity.Id">Редактировать</a>
                <form style="display:inline-block" id="form-@entity.Id" asp-area="Admin" asp-controller="ProjectItems" asp-action="Delete" method="post">
                    <input type="hidden" name="id" value="@entity.Id" />
                    <a onclick="document.getElementById('form-@entity.Id').submit()">Удалить</a>
                </form>

                <a asp-area="Admin" asp-controller="Projects" asp-action="Index" asp-route-id="@entity.Id">
                    @($"{entity.Title}")
                </a>
            }
        </div>
    }
    <div class="container">
        <h3>Редактирование страниц сайта</h3>
        <a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageIndex">Главная</a>
        <a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageProjects">Проекты</a>
        <a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageContacts">Контакты</a>
    </div>
    <div class="container">
        <form asp-area="" asp-controller="Account" asp-action="Logout" method="post">
            <input type="submit" name="logout" value="Выйти" />
        </form>
    </div>
</div>

ASPNetApp/Areas/Admin/Views/ProjectItems/Edit.cshtml
@model ProjectItem

@{
    ViewData["Title"] = "Редактирование проекта.";
}


<script src="~/js/ckeditor5-build-classic/ckeditor.js"></script>

<div class="container">
    <h1>Редактирование проекта</h1>
    <div class="container">
        <form asp-area="Admin" asp-controller="ProjectItems" asp-action="Edit" method="post" enctype="multipart/form-data">
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="AddingDate" />
            <input type="hidden" asp-for="CodeWord" />
            <div asp-validation-summary="All"></div>
            <div class="container">
                <label asp-for="Title"></label>
                <input asp-for="Title" />
                <span asp-validation-for="Title"></span>
            </div>
            <div class="container">
                <label asp-for="Text"></label>
                <textarea asp-for="Text" class="ckedit"></textarea>
                <span asp-validation-for="Text"></span>
            </div>
            <div class="container">
                <label asp-for="Technologies"></label>
                <input asp-for="Technologies" />
                <span asp-validation-for="Technologies"></span>
            </div>
            <div class="container">
                <label asp-for="ShortDescription"></label>
                <input asp-for="ShortDescription" />
                <span asp-validation-for="ShortDescription"></span>
            </div>
            <div class="container">
                <label asp-for="UrlToPreview"></label>
                <input type="file" name="UrlToPreview" asp-for="UrlToPreview" />
                <div>
                    <img style="width:400px" src="~/images/@Model.UrlToPreview" />
                </div>
            </div>
            <div class="container">
                <label asp-for="MetaTitle"></label>
                <input asp-for="MetaTitle" />
                <span asp-validation-for="MetaTitle"></span>
            </div>
            <div class="container">
                <label asp-for="MetaDescription"></label>
                <input asp-for="MetaDescription" />
                <span asp-validation-for="MetaDescription"></span>
            </div>
            <div class="container">
                <label asp-for="MetaKeywords"></label>
                <input asp-for="MetaKeywords" />
                <span asp-validation-for="MetaKeywords"></span>
            </div>
            <input type="submit" />
        </form>
    </div>
</div>
<script>
    ClassicEditor
        .create(document.querySelector('#Text'))
        .then(editor => {
            console.log(editor);
        })
        .catch(error => {
            console.error(error);
        });
</script>

ASPNetApp/Areas/Admin/Views/TextFields/Edit.cshtml
@model TextField


@{
    ViewData["Title"] = "Редактирование страниц сайта";
}




<div class="container">
    <h1>Редактирование полей сайта</h1>
    <div class="container">
        <form asp-area="Admin" asp-controller="TextFields" asp-action="Edit" method="post" enctype="multipart/form-data">
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="AddingDate" />
            <input type="hidden" asp-for="CodeWord" />
            <div asp-validation-summary="All"></div>
            <div class="container">
                <label asp-for="Title"></label>
                <input asp-for="Title" />
                <span asp-validation-for="Title"></span>
            </div>
            <div class="container">
                <label asp-for="Text"></label>
                <textarea asp-for="Text" style="height: 200px; slide"></textarea>
                <span asp-validation-for="Text"></span>
            </div>
            <div class="container">
                <label asp-for="MetaTitle"></label>
                <input asp-for="MetaTitle" />
                <span asp-validation-for="MetaTitle"></span>
            </div>
            <div class="container">
                <label asp-for="MetaDescription"></label>
                <input asp-for="MetaDescription" />
                <span asp-validation-for="MetaDescription"></span>
            </div>
            <div class="container">
                <label asp-for="MetaKeywords"></label>
                <input asp-for="MetaKeywords" />
                <span asp-validation-for="MetaKeywords"></span>
            </div>
            <input type="submit" />
        </form>
    </div>
</div>


<script type="text/javascript">
    $(document).ready(function () {
        $("#Text").markItUp(mySettings);
    });
</script>

ASPNetApp/Views/Shared/Contacts.cshtml
@model TextField

<div>
    @Html.Raw(HttpUtility.HtmlDecode(Model.Text))
</div>

ASPNetApp/Views/Shared/CssPartial.cshtml
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
<!-- My Styles -->
<link href="https://fonts.googleapis.com/css2?family=Yanone+Kaffeesatz:wght@300&display=swap" rel="stylesheet">
<link rel="stylesheet" href="~/css/styles.css">
<link href="https://fonts.googleapis.com/css2?family=Cutive+Mono&family=Russo+One&display=swap" rel="stylesheet">

ASPNetApp/Views/Shared/FooterPartial.cshtml
<footer class="bg-dark">
    <div>
        <p class="text-muted">© @Config.UserName 2020</p>
    </div>
</footer>

ASPNetApp/Views/Shared/HeaderPartial.cshtml
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-dark">
        <a class="navbar-brand" href="#">
            <img id="mylogo" src="~/images/code.svg">
        </a>
        <div class="logotext">@Config.UserName</div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <!--            <label class="ml-5"><input type="checkbox"><span>COMIC SANS</span><img id="sans" src="images/s1200.png"></label>
        <label class="ml-5"><input type="checkbox"><span>PAPYRUS REGULAR</span><img id="sans" src="images/93321-area-artwork-animation-sprite-undertale-free-download-png-hq.png"></label>-->
        <div class="collapse navbar-collapse mr-5" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Me">Обо мне</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Проекты
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="#">Десктопные приложения</a>
                        <a class="dropdown-item" href="#">Алгоритмы</a>
                        <a class="dropdown-item" href="#">Веб-приложения</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" asp-area="" asp-controller="Projects" asp-action="Index" asp-route-id="">Все проекты</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Contacts">Контакты</a>
                </li>
            </ul>
        </div>
    </nav>
</header>

ASPNetApp/Views/Shared/Index.cshtml
@model DataManager

<div>
    @Html.Raw(HttpUtility.HtmlDecode(Model.TextFields.GetTextFieldByCodeWord("PageIndex").Text))
</div>
@await Html.PartialAsync("ProjectsPartial")

ASPNetApp/Views/Shared/IntroductionPartial.cshtml
<div class="parallax-header container-fluid" data-stellar-background-ratio="0.7">
    <div class="back-overlay"></div>
    <div class="hello-text">
        <p>Добро пожаловать на сайт визитку</p>
        <p>разработчика ПО!</p>
    </div>
</div>

ASPNetApp/Views/Shared/MainPartial.cshtml
<section class="bg-light">
    <div id="information" class="container-fluid">
        <div class="row">
            <div class="col border" align="center">
                <h2 class="my-article">Мои навыки</h2>
                <hr>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <img src="images/hashtag.svg" alt="">
                        <div class="progress">
                            <div class="progress-bar progress-bar-striped progress-bar-animated bg-info" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: 75%"></div>
                        </div>
                    </li>
                    <li class="list-group-item">
                        <img src="images/java.svg" alt="">
                        <div class="progress">
                            <div class="progress-bar progress-bar-striped progress-bar-animated bg-warning" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: 55%"></div>
                        </div>
                    </li>
                    <li class="list-group-item">
                        <img src="images/html.svg" alt="">
                        <div class="progress">
                            <div class="progress-bar progress-bar-striped progress-bar-animated bg-danger" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: 40%"></div>
                        </div>
                    </li>
                    <li class="list-group-item">
                        <img src="images/css.svg" alt="">
                        <div class="progress">
                            <div class="progress-bar progress-bar-striped progress-bar-animated bg-primary" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: 30%"></div>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="col-7 border text-center">
                <div class="single-post my-article">
                    <h1 class="post-category" align="center" style="color:coral">Who Am I</h1>
                    <hr>
                    <div class="article-text-style">
                        <p>Добро пожаловать на мой личный сайт-визитку!</p>
                        <p>Меня зовут Никита и я разработчик!</p>
                        <p>Я являюсь студентом Воронежского Опорного Университета и уже третий курс обучаюсь на направлении Информационные системы и технологии.</p>
                        <p>
                            Занимаюсь разработкой приложений преимущественно на языке C#. Пробую также другие языки программирования и всё ещё ищу подходящее мне направление разработки.
                        </p>
                    </div>
                </div>
            </div>
            <div class="col border" align="center">
                <h2 class="my-article">Мои хобби</h2>
                <hr>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <img src="images/guitar.svg" alt="">
                        <hr>
                        <p>Музыка</p>
                    </li>
                    <li class="list-group-item">
                        <img src="images/game-controller.svg" alt="">
                        <hr>
                        <p>Гейминг</p>
                    </li>
                    <li class="list-group-item">
                        <img src="images/bike.svg" alt="">
                        <hr>
                        <p>Велопрогулки</p>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</section>
<section class="bg-light">
    <hr>
    <div class="container mr-auto">
        <h1 align="center">Мои проекты</h1>
    </div>
    <hr>
    <div class="grid-posts mt-1">
        <div class="container">
            <div class="row row-cols-2 row-cols-md-3">
                <div class="col mb-4">
                    <div class="card-body">
                        <img src="images/Vk_Attachments_Screen_1.PNG" alt="...">
                        <h5 class="card-title">Polyphone</h5>
                        <p class="card-text">Фонетический алгоритм для кодирования слов. Используется для поиска ошибок в запросах.</p>
                        <button type="button" class="btn btn-primary">Github</button>
                    </div>
                    <div class="card-footer">
                        <small class="text-muted">C#</small>
                    </div>
                </div>
                <div class="col mb-4">

                    <div class="card-body">
                        <img src="images/Vk_Attachments_Screen_1.PNG" alt="...">
                        <h5 class="card-title">Vk-Attachments</h5>
                        <p class="card-text">Приложение позволяющее скачивать вложения из бесед социальной сети Вконтакте.</p>
                        <button type="button" class="btn btn-primary">Github</button>
                    </div>
                    <div class="card-footer">
                        <small class="text-muted">C#, WPF</small>
                    </div>
                </div>
                <div class="col mb-4">

                    <div class="card-body">
                        <img src="images/Interface.PNG" alt="...">
                        <h5 class="card-title">Perlin Noise</h5>
                        <p class="card-text">Визуализации математической функции: шумы Перлина, использующейся в процедурной генерации</p>
                        <button type="button" class="btn btn-primary">Github</button>
                    </div>
                    <div class="card-footer">
                        <small class="text-muted">C#, WPF</small>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

ASPNetApp/Views/Shared/MetatagsPartial.cshtml
@using ASPNetApp.Service
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta http-equiv="cache-control" content="no-cache">
<meta http-equiv="expires" content="0">
@if (ViewBag.Title != null)
{
    <title>@ViewBag.Title</title>
}
else
{
    <title>@Config.UserName</title>
}

@if (ViewBag.Description != null)
{
    <meta name="description" content="@ViewBag.Description" />
}
else
{
    <meta name="description" content="Портфолио одного очень упорного программиста" />
}

@if (ViewBag.Keywords != null)
{
    <meta name="keywords" content="@ViewBag.Keywords" />
}

ASPNetApp/Views/Shared/ProjectsPartial.cshtml
@model DataManager


<section class="bg-light">
    <hr>
    <div class="container mr-auto">
        <h1 align="center">Мои проекты</h1>
    </div>
    <hr>
    <div class="grid-posts mt-1">
        <div class="container">
            <div class="row row-cols-2 row-cols-md-3">

                @foreach (var project in Model.ProjectItems.GetAllProjectItems())
                {
                    <div class="col mb-4">

                        <div class="card-body">
                            <img src="~/images/@project.UrlToPreview" alt="...">
                            <h5 class="card-title">@project.Title</h5>
                            <p class="card-text">@project.ShortDescription</p>
                            <button type="button" class="btn btn-primary">Github</button>
                        </div>
                        <div class="card-footer">
                            <small class="text-muted">@project.Technologies</small>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</section>

ASPNetApp/Views/Shared/ScriptsPartial.cshtml
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script type="text/javascript" src="~/js/jquery.pack.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<script src="~/js/Stellar.js"></script>
<script src="~/js/scripts.js"></script>
<script type="text/javascript" src="~/js/markitup/jquery.markitup.js"></script>
<script type="text/javascript" src="~/js/markitup/sets/default/set.js"></script>
<link rel="stylesheet" type="text/css" href="~/js/markitup/skins/markitup/style.css" />
<link rel="stylesheet" type="text/css" href="~/js/markitup/sets/default/style.css" />

ASPNetApp/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>
<!--
    Escape Velocity by HTML5 UP
    html5up.net |
    Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
<head>
    @await Html.PartialAsync("MetatagsPartial")
    @await Html.PartialAsync("CssPartial")
    @await Html.PartialAsync("ScriptsPartial")
</head>
<body>
    <div>

        @await Html.PartialAsync("HeaderPartial")
        @await Html.PartialAsync("IntroductionPartial")
        @RenderBody()
        <!-- Main -->

    </div>

    @await Html.PartialAsync("FooterPartial")
</body>
</html>